# Generated by Django 6.0.6 on 2026-06-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_portfoliocategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocategory',
            name='name',
            field=models.CharField(choices=[('Design', 'Design'), ('Data Scraping', 'Data Scraping'), ('Research', 'Research'), ('Data Entry', 'Data Entry'), ('Automation', 'Automation'), ('AI', 'AI'), ('Web Development', 'Web Development'), ('Video', 'Video'), ('Training & Education', 'Training & Education')], max_length=50),
        ),
    ]
