# Generated by Django 6.0.6 on 2026-06-12 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_portfoliocategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.portfoliocategory')),
            ],
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.portfoliosubcategory'),
        ),
    ]
