# Generated by Django 6.0.6 on 2026-06-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_portfolioitem_cover_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='cover_ratio',
            field=models.CharField(choices=[('1/1', 'Square (1:1)'), ('4/3', 'Standard (4:3)'), ('3/2', 'Photo (3:2)'), ('16/9', 'Widescreen (16:9)'), ('21/9', 'Ultra Wide (21:9)'), ('4/5', 'Portrait (4:5)'), ('9/16', 'Vertical (9:16)'), ('1.91/1', 'Social Banner (1.91:1)'), ('1/1.414', 'A4 Document')], default='16:9', help_text='Select the layout type (e.g., 16:9 for videos, 1:1 for logos)', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfoliomedia',
            name='aspect_ratio',
            field=models.CharField(choices=[('1/1', 'Square (1:1)'), ('4/3', 'Standard (4:3)'), ('3/2', 'Photo (3:2)'), ('16/9', 'Widescreen (16:9)'), ('21/9', 'Ultra Wide (21:9)'), ('4/5', 'Portrait (4:5)'), ('9/16', 'Vertical (9:16)'), ('1.91/1', 'Social Banner (1.91:1)'), ('1/1.414', 'A4 Document')], default='16:9', help_text='Select the layout type (e.g., 16:9 for videos, 1:1 for logos)', max_length=20),
        ),
    ]
